repo: openworm/ChannelWorm
shortDescription: "A repository to integrate data, information, scripts, and models of ion channels in C. elegans"
coordinator: stephen@openworm.org
documentation: "https://channelworm.readthedocs.io/en/latest/"
earnable-badges: 
  - "http://www.badgelist.com/OpenWorm/Hodgkin-Huxley-Tutorial-Graduate"
gitter: "http://gitter.im/openworm/ChannelWorm"
keywords: 
  - database
  - data
  - cells
  - channels
languages: 
  - python
members: 
  - vahidghayoomi@gmail.com
  - milad.jafary@gmail.com 
outputs: 
  - openworm/muscle_model
  - openworm/CElegansNeuroML
parent: 
  - openworm/OpenWorm
tests: true
